config/routes.rb
Bearbnb::Application.routes.draw do
  devise_for :users

  get 'search', to: 'listings#index'

  resources :users do
    resources :listings do
      resources :reservations
      resources :photos
    end
  end

  resources :reviews
  resources :calendars, :only => [:create]

  resources :amenities do
    resources :tags
  end
  root to: 'listings#index'
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :reviews, as: :commentable

  has_many :tags
  has_many :amenities, :through => :tags


  def self.search_by_city(query)
    Listing.where("lower(city) = ?", query.downcase).to_a
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    if params[:search].nil?
      @listings = Listing.all
    else
      @listings = Listing.search_by_city(params[:search])
      if @listings.length < 1
        flash[:alert] = "No results found"
      end
    end
  end

  def new
    @listing = Listing.new
  end

  def show
    @listing = Listing.find(params[:id])
    @photo = Photo.new
    @user = User.find(params[:user_id])
    @reservations = @listing.reservations
    @reservation = Reservation.new
    @tags = @listing.tags
    @review = Review.new
    @reviews = @listing.reviews
    @amenities = Amenity.all - @listing.amenities
  end

  def create
    @user = User.find(params[:user_id])
    @listing = Listing.new(listing_params)
    @user.listings << @listing

    if @listing.save
      flash[:notice] = "Your Listing Has Been Created!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "There Was a Problem With Your Listing."
      render 'new'
    end
  end

  def edit
    @listing = Listing.find(params[:id])
    @user = @listing.user
    @photo = Photo.new
  end

  def update
    @user = User.find(params[:user_id])
    @listing = Listing.find(params[:id])

    if @listing.update(listing_params)
      flash[:notice] = "Your Listing Has Been Updated!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "There Was a Problem With Your Listing."
      render 'edit'
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to root_path
  end

  private
    def listing_params
      params.require(:listing).permit(:search, :address, :city, :bedroom_count, :bathroom_count, :bed_type, :room_type, :description, :nightly_rate, :weekly_rate, :monthly_rate)
    end

end

app/views/listings/_calendar.html.erb
<div id="calendar" class="col-lg-12">

  <% @this_month = Date.new(@year, @month.to_i, 1) %>

  <div class="month-header"><%= @this_month.strftime("%B") %></div>
  <div class="day-header">Sunday</div><div class="day-header">Monday</div><div class="day-header">Tuesday</div><div class="day-header">Wednesday</div><div class="day-header">Thursday</div><div class="day-header">Friday</div><div class="day-header">Saturday</div>
  <%
    month = @this_month.strftime("%m").to_i
    all_bookings = {2014 => [], 2015 => [], 2016 => []}
    @reservations.map do |res|
      for x in 0...res.checkout - res.checkin
        all_bookings[(res.checkin + x).strftime("%Y").to_i] << (res.checkin + x).yday
      end
    end
    spaces = Time.days_in_month(@this_month.strftime("%m").to_i, @this_month.strftime("%Y").to_i) + @this_month.wday
    add_on_spaces = 7 - (spaces % 7)
    counter = 0
    # breakere
  %>
  <% for i in 1..spaces do %>
    <div class="day-box" id="day-<%= i %>">
      <% if i > @this_month.wday && i <= spaces %>
        <% counter += 1 %>
        <span class="day-num"><%= counter %></span>
        <% if all_bookings[@year].include?(Date.new(@year, @month.to_i, counter).yday) %>
            <span class="booking">Booked</span>
        <% end %>
      <% else %>
        <span class="other-month"></span>
      <% end %>
    </div>
  <% end %>
  <% add_on_spaces.times do %>
    <div class="day-box"><span class="other-month"></span></div>
  <% end %>
</div>

app/views/listings/_form.html.erb
<div class="col-md-6">

  <%= form_for [current_user, @listing] do |f| %>

  <div class="form-group">
    <%= f.label :address, 'Street Address:', class: 'sr-only' %>
    <%= f.text_field :address, autofocus: true, placeholder: 'Street Address', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :city, 'City:', class: 'sr-only' %>
    <%= f.text_field :city, placeholder: 'City', class: 'form-control' %>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-sm-6">
        <%= f.number_field :bedroom_count, placeholder: 'Bedroom Count', class: 'form-control' %>
      </div>
      <div class="col-sm-6">
        <%= f.number_field :bathroom_count, placeholder: 'Bathroom Count', class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, 'Description:', class: 'sr-only' %>
    <%= f.text_area :description, placeholder: 'Description', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :bed_type, 'Bed Type:' %>
    <%= f.select :bed_type, options_for_select([['Bed','Bed'], ['Air Mattress','Air Mattress'], ['Futon','Futon'], ['Couch','Couch'], ['Floor','Floor']]), class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :room_type, 'Room Type:' %>
    <%= f.select :room_type, options_for_select([['Private','Private'], ['Shared','Shared']]), class: 'form-control' %>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-sm-12">
        <label>Rates:</label>
      </div>
      <div class="col-sm-4">
        <%= f.number_field :nightly_rate, placeholder: 'Daily Rate', class: 'form-control' %>
      </div>
      <div class="col-sm-4">
        <%= f.number_field :weekly_rate, placeholder: 'Weekly', class: 'form-control' %>
      </div>
      <div class="col-sm-4">
        <%= f.number_field :monthly_rate, placeholder: 'Monthly', class: 'form-control' %>
      </div>
    </div>
  </div>
  <%= f.submit "Submit", :class => 'btn btn-info' %>
<% end %>

</div>

app/views/listings/edit.html.erb
<h2>Edit Your Listing</h2>

<div class="row">
  <%= render 'form' %>
</div>

<hr>

<h2>Photos</h2>

<div class="row">
  <div id="photos" class="col-lg-12">
    <% @listing.photos.each do |photo| %>
      <%= link_to (image_tag photo.picture.url(:thumb)), photo.picture.url(:medium), class: 'fancybox', title: photo.caption, rel: 'fb-group' %>
    <% end %>
  </div>
</div>

app/views/listings/index.html.erb
<h2>Welcome to Bear BNB</h2>
<h3>Check out some of our listings!</h3>

<hr>

<% @listings.each do |listing| %>

  <div class="listing-index">
    <div class="listing-info">
      <%= listing.address %>
    </div>

    <% if listing.photos.length > 0 %>
      <%= link_to (image_tag listing.photos.first.picture.url(:medium), class: 'listing-bg'), user_listing_path(listing.user, listing) %>
    <% else %>
      <%= link_to (image_tag 'http://cdn.freshome.com/wp-content/uploads/2009/06/Hello-Kitty-House-in-Shanghai-1.jpg', class: 'listing-bg'), user_listing_path(listing.user, listing) %>
    <% end %>
  </div>

<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

app/views/listings/results.html.erb
<% @search_results.each do |result| %>

  <div class="listing-index">
    <div class="listing-info">
      <%= result.address %>
    </div>

    <% if result.photos.length > 0 %>
      <%= link_to (image_tag result.photos.first.picture.url(:medium), class: 'listing-bg'), user_result_path(result.user, result) %>
    <% else %>
      <%= link_to (image_tag 'http://cdn.freshome.com/wp-content/uploads/2009/06/Hello-Kitty-House-in-Shanghai-1.jpg', class: 'listing-bg'), user_result_path(result.user, result) %>
    <% end %>
  </div>

<% end %>

app/views/listings/show.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-6">
      <h1><%= @listing.address %></h1>

      <p><%= @listing.description %></p>
      <p><%= render 'layouts/errors', object: @review %></p>

      <% if current_user != @listing.user %>
        <%= link_to 'Book It', '#', class: 'btn btn-danger', data: { toggle: 'modal', target: '#makeReservation'} %>
      <% end %>
    </div>
    <div class="col-md-3">
      Details:
      <ul>
        <li>Bed(s): <%= @listing.bed_type %></li>
        <li>Room(s): <%= @listing.room_type %></li>
        <li>Bedroom(s): <%= @listing.bedroom_count %></li>
        <li>Bathroom(s): <%= @listing.bathroom_count %></li>
      </ul>
    </div>
    <div class="col-md-3">
      Rates:
      <ul>
        <li>Daily: $<%= @listing.nightly_rate.to_i %></li>
        <li>Weekly: $<%= @listing.weekly_rate.to_i %></li>
        <li>Monthy: $<%= @listing.monthly_rate.to_i %></li>
      </ul>
    </div>
  </div>
  <hr>

  <div class="row">
    <div id="listing-tags" class="col-lg-12">
        <ul>
          <% @tags.each do |tag| %>
              <li>
                <% if current_user == @listing.user %>
                  <%= link_to tag.amenity.name, amenity_tag_path(tag.amenity, tag), remote: true,  method: 'delete', id: "destroy-am-#{tag.id}" %>
                <% else %>
                  <%= link_to tag.amenity.name, '#' %>
                <% end %>
              </li>
          <% end %>
        </ul>
    </div>
  </div>

  <div class="row">
    <div id="photos" class="col-lg-12">
      <% @listing.photos.each do |photo| %>
        <div class="photo-thumbs">
          <%= link_to (image_tag photo.picture.url(:thumb)), photo.picture.url(:medium), class: 'fancybox photo-thumb', title: photo.caption, rel: 'fb-group', id: "destroy-#{photo.id}" %>
        </div>
        <% if current_user == @listing.user %>
          <div class="photo-buttons">
            <%= link_to "Delete", user_listing_photo_path(@user, @listing, photo),
                             :data => {:confirm => "Are you sure?",
                                       :method => "delete"},
                             :class => "btn btn-danger btn-xs", :id => "delete-button-#{photo.id}", remote: true %></p>
            <%= link_to 'Edit Caption', "#", class: 'btn btn-success btn-xs', data: { toggle: 'modal', target: '#editCaption'} %>
          </div>
        <% end %>
        <div class="modal fade" id="editCaption" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Edit Caption</h4>
              </div>
              <div class="modal-body">
                <%= form_for [@user, @listing, photo], method: "patch" do |f| %>
                  <div class="form-group">
                    <%= f.label :caption %>
                    <%= f.text_field :caption, class: 'form-control', placeholder: "Describe the picture..." %> 
                  </div>
                  <%= f.submit 'Submit', class: 'btn btn-info' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <hr>

  <ul class="nav nav-tabs">
    <li class="active"><a href="#calendar-pane" data-toggle="tab">Calendar</a></li>
    <li><a href="#review-pane" data-toggle="tab">Reviews</a></li>
    <% if current_user == @listing.user %>
      <li><a href="#editor-pane" data-toggle="tab">Edit Listing</a></li>
    <% end %>
  </ul>
  <div class="tab-content">

  <div class="tab-pane active" id="calendar-pane">

    <% @month = Date.today.strftime("%m")
       @year = Date.today.strftime("%Y").to_i
    %>

    <% @this_month = Date.new(@year, @month.to_i, 1) %>

    <%= form_tag calendars_path(listing_id: @listing.id, user_id: @listing.user), id: 'calendar-form', remote:true do %>
      <div class="row">
        <div class="col-md-3">
          <%= select_tag :month, options_for_select([['January', 1], ['February',2], ['March',3], ['April',4], ['May',5], ['June',6], ['July',7], ['August',8], ['September',9], ['October',10], ['November',11], ['December',12]], @month.to_i), class: 'form-control' %>
        </div><div class="col-md-3">
          <%= select_tag :year, options_for_select([['2014', 2014], ['2015',2015], ['2016',2016]], @year.to_i), class: 'form-control' %>
        </div><div class="col-md-3">
          <%= submit_tag 'Submit' %>
        </div>
      </div>
    <% end %>

    <div class="row" id="cal-row">
      <%= render '/listings/calendar' %>
    </div>
  <div class="clear"></div>

  </div>


  <div class="tab-pane" id="review-pane">

  <div class="row">

    <div class="col-md-6">
      <h4>Reviews</h4>

      <% if @listing.reservations.where(user_id: current_user.id).length > 0 && current_user != @listing.user %>

        <div class="panel panel-default">
          <div class="panel-heading">Add a listing review</div>
          <div class="panel-body">
            <%= form_tag reviews_path(listing_id: @listing.id, user_id: current_user.id) do %>
              <div class="form-group">
                <%= label_tag :rating, 'Rating: ' %>
                <%= select_tag :rating, options_for_select([[5,5],[4,4],[3,3],[2,2],[1,1]]), class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= text_area_tag :description, '', placeholder: 'Say something...' ,rows: 5, class: 'form-control' %>
              </div>
              <%= submit_tag 'Submit', class: 'btn, btn-primary'  %>
            <% end %>
          </div>
        </div>
      <% end %>

      <% @reviews.each do |review| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to review.user.name, user_path(review.user) %>
            <div class="star-rating"><%= '★' * review.rating %><%= '☆' * (5 - review.rating) %></div>
          </div>
          <div class="panel-body">
            <div class="col-md-4">
              <%= link_to (image_tag review.user.avatar.url(:thumb)), user_path(review.user) %>
            </div>
            <div class="col-md-6">
              <div class="row">
                <%= review.description %>
              </div>
            </div>
          </div>
          <div class="panel-footer">
            <%= time_ago_in_words(review.created_at) %> ago.
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="clear"></div>

  </div>

  <div class="tab-pane" id="editor-pane">

  <% if current_user.id == @listing.user_id %>
    <div class="row">
      <div class="col-md-5">
        <%= form_for [@user, @listing, @photo], remote: true, authenticity_token: true, html: { :multipart => true } do |f| %>
          <div class="form-group">
            <%= f.label :picture, "Add a Photo" %>
            <%= f.file_field :picture %>
          </div>
          <div class="form-group">
            <%= f.label :caption %>
            <%= f.text_field :caption, class: 'form-control', placeholder: "Describe the picture..." %> 
          </div>
          <%= f.submit 'Submit', class: 'btn btn-info' %>
        <% end %>
      </div>
      <h2>Edit Your Listing</h2>
      <%= render 'form' %>
      <div class="row">
      <div class="col-md-6"  id="add-amenities">
      <h3>Add Amenities:</h3>
        <ul>
          <% @amenities.each do |am| %>
            <li><%= link_to am.name, amenity_tags_path(am, :listing_id => @listing.id), method: 'post', id: "am-#{am.id}", remote: true %></li>
          <% end %>
        </ul>
      </div>
      </div>
    </div>
  <% end %>
<div class="clear"></div>

</div>

</div>

<div class="modal fade" id="makeReservation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Make Reservation</h4>
        </div>
        <div class="modal-body">
          <%= form_for [@user, @listing, @reservation], :role => 'form' do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="form-group">
              <%= f.label :checkin, 'Check In Date:' %>
              <%= f.date_field :checkin, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :checkout, 'Check Out Date:' %>
              <%= f.date_field :checkout, class: 'form-control' %>
            </div>
            <%= f.submit 'Submit', class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>