config/routes.rb
Bearbnb::Application.routes.draw do
  devise_for :users

  get 'search', to: 'listings#index'

  resources :users do
    resources :listings do
      resources :reservations
      resources :photos
    end
  end

  resources :reviews
  resources :calendars, :only => [:create]

  resources :amenities do
    resources :tags
  end
  root to: 'listings#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings
  has_many :reservations
  has_many :reviews

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @listings = @user.listings
  end

  private
    def user_params
      params.require[:user].permit(:name, :email, :password, :password_confirmation, :current_password, :avatar, :bio)
    end
end

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-5">
    <% if !@user.avatar_file_name.nil? %>
      <%= image_tag @user.avatar.url(:medium) %>
    <% end %>
  </div>
  <div class="col-md-7">
    <h2>Hi, I'm <%= @user.name %>!</h2>
    <h5>Member for <%= time_ago_in_words(@user.created_at) %></h5>
    <%= @user.bio %>
    <hr>
    <span class="glyphicon glyphicon-pencil"></span>
    <%= link_to 'Edit Profile', edit_user_registration_path %> |
    <span class="glyphicon glyphicon-plus"></span>
    <%= link_to 'New Listing', new_user_listing_path(current_user) %>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h2>Listings:</h2>
    <% @listings.each do |listing| %>
      <div class="user-listing">
        <span class="glyphicon glyphicon-home"></span>
        <%= link_to listing.address, user_listing_path(current_user, listing) %>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2>Future Bookings</h2>
    <% @user.reservations.each do |reservation| %>
      <div class="user-reservation">
        <span class="glyphicon glyphicon-certificate"></span>
        <%= link_to reservation.listing.address, user_listing_path(reservation.user, reservation.listing) %>
        <span class="booking-dates"><%= reservation.checkin.strftime("%m/%d/%y") %> - <%= reservation.checkout.strftime("%m/%d/%y") %></span>
      </div>
    <% end %>
  </div>
</div>